### ISSUE TITLE
provide more user friendly error message if ontology is incoherent

### ISSUE THREAD

**Issue by cmungall** [balhoff/relation-graph#101]
```bash
wget http://purl.obolibrary.org/obo/cheminf.owl -O owl/cheminf.owl
relation-graph --ontology-file owl/cheminf.owl --output-file inferences/cheminf-inf.ttl
```

makes a giant stack trace. scroll up and you can see the ontology is incoherent

consider: non-strict option that will drop all constraining axioms if ontology is incoherent. it is awkward to do this with robot as part of a pipeline, and sometimes we just want the graph walking regardless of some bfo nonsense at the top

**Comment by balhoff** [comment]
I added an option `--disable-owl-nothing true`, which uses a special feature of Whelk. But that ontology is inconsistent; there's a problem with individuals. The Whelk option only works for the EL algorithm, not the RL part.
