### ISSUE TITLE
Unsatisfiable classes even when passing --disable-owl-nothing

### ISSUE THREAD

**Issue by cmungall** [balhoff/relation-graph#127]
```bash
robot merge -I http://purl.obolibrary.org/obo/upheno.owl -o db/upheno.owl
relation-graph --disable-owl-nothing true \
                       --ontology-file db/upheno.owl\
                       --output-file db/upheno-relation-graph.tsv.ttl.tmp \
                       --equivalence-as-subclass true \
                       --output-subclasses true \
                       --reflexive-subclasses true
```

yields

```
2022.05.16 16:22:47:341 zio-default-async-1 INFO org.renci.relationgraph.Main.program:57
    Running reasoner
2022.05.16 16:28:28:181 zio-default-async-1 INFO org.renci.relationgraph.Main.program:60
    Done running reasoner
2022.05.16 16:28:28:257 zio-default-async-1 ERROR org.renci.relationgraph.Main.run:77
    Ontology is incoherent; please correct unsatisfiable classes.
```

From #101 it seems maybe that `--disable-owl-nothing` is not sufficient in itself, although this ontology should not have individuals, and the error is about correcting unsatisfiable classes. Perhaps it is the case the RL part does things like check for disjointness violations as rules regardless of owl-nothing?

While we should fix upheno, it would be good to have a mode that is for just calculating the relation graph from nothing more than RBox axioms, subClassOf, someValuesFrom (perhaps classAssertion). While this can be done as a robot step it's convenient to do directly

**Comment by balhoff** [comment]
Should be fixed by #132.
