### ISSUE TITLE
Output is not valid n-triples

### ISSUE THREAD

**Issue by cmungall** [balhoff/relation-graph#140]
Latest versions of RG use the turtle `a` shorthand for rdf:type

This isn't valid n-triples:
https://www.w3.org/TR/n-triples/#grammar-production-IRIREF

Now, strictly speaking this is not a problem. The documentation gives no guarantee about the format, and the output is valid turtle.

However, it looks **sufficiently like** n-triples that it fools some tools - for example:

```
➜  semantic-sql git:(adding-sources) ✗ cat foo 
<http://www.reactome.org/biopax/81/48887#CellularLocationVocabulary88> a <http://www.biopax.org/release/biopax-level3.owl#CellularLocationVocabulary> .
➜  semantic-sql git:(adding-sources) ✗ riot foo
11:54:09 ERROR riot            :: [line: 1, col: 72] Expected IRI: Got: [KEYWORD:a]
```

For jena, this is obviated by either giving a file suffix OR with an explicit `--syntax`

However, it still seems a bit of a bait and switch - either use idiomatic nested turtle or use pure n-triples.

It may also be the case that forcing use of a turtle parser would be slower (just checked: it looks like with Jena parsing as turtle vs a using n-triples parser with explicit rdf:types takaes 5% longer, nbd, but other toolchains may be different)

some of this is maybe irrelevant with a TSV format which will allow guaranteed streaming parsing

**Comment by balhoff** [comment]
Thanks for noticing this! I'm using Jena's `RDFFormat.TURTLE_FLAT` which supports streaming output, but I also have been relying on N-Triples compatibility in various projects. I will enforce N-Triples.
