### ISSUE TITLE
including a non-existent URI in a properties-file results in zero results

### ISSUE THREAD

**Issue by cmungall** [balhoff/relation-graph#156]
If I include a non-URI or a URI that does not correspond to an OP in the ontology in my properties file, something silently fails, and the resulting rdf file is empty.

Also: an empty properties file leads to all properties being used. This is potentially useful as a kind of default behavior but maybe surprising.

**Comment by balhoff** [comment]
Thanks for catching this! I added info about the default behavior to the CLI docs.
